web/Models/Record.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;

namespace YAOJ.Models
{
    public static class Extensions
    {
        /// <summary>
        ///     A generic extension method that aids in reflecting 
        ///     and retrieving any attribute that is applied to an `Enum`.
        /// </summary>
        public static TAttribute GetAttribute<TAttribute>(this Enum enumValue)
                where TAttribute : Attribute
        {
            return enumValue.GetType()
                            .GetMember(enumValue.ToString())
                            .First()
                            .GetCustomAttribute<TAttribute>();
        }

        public static string GetDisplayName(this Enum enumValue)
        {
            return enumValue.GetAttribute<DisplayAttribute>().Name;
        }
    }

    public enum Status
    {
        [Display(Name = "Time Limit Exceeded")]
        TLE,
        [Display(Name = "Memory Limit Exceeded")]
        MLE,
        [Display(Name = "Runtime Error")]
        RE,
        [Display(Name = "Compilation Error")]
        CE,
        [Display(Name = "Accepted")]
        AC,
        [Display(Name = "Wrong Answer")]
        WA,
        [Display(Name = "Not Available")]
        NA
    }

    public class Record
    {
        [Key]
        [DisplayName("Record ID")]
        public int RecordID { get; set; }

        [DisplayName("Status")]
        public Status Status { get; set; }

        [DisplayName("User")]
        public User User { get; set; }
        
        [DisplayName("Problem ID")]
        public Problem Problem { get; set; }

        public int UserID { get; set; }
        public string ProblemID { get; set; }

        [DisplayName("Language")]
        public string Language { get; set; }

        [DisplayName("Source Code")]
        public string SourceCode { get; set; }

        [DisplayName("Used Time")]
        public double UsedTime { get; set; }

        [DisplayName("Used Memory")]
        public double UsedMemory { get; set; }
        
        [DisplayName("Judge Text")]
        public string JudgeText { get; set; }
    }
}

web/Controllers/ProblemsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using YAOJ.Data;
using YAOJ.Models;

namespace YAOJ.Controllers
{
    public class ProblemsController : Controller
    {
        static string GetMd5Hash(byte[] data)
        {
            var sb = new StringBuilder();
            using (var md5Hash = MD5.Create())
            {
                var hashData = md5Hash.ComputeHash(data);
                for (var i = 0; i < hashData.Length; ++i)
                {
                    sb.Append(hashData[i].ToString("x2"));
                }
            }
            return sb.ToString();
        }

        private readonly DataContext _context;
        private readonly IConfiguration _configuration;

        public ProblemsController(DataContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        // GET: Problems
        public async Task<IActionResult> Index(int? page)
        {
            int pageSize = 10;

            return View(await PaginatedList<Problem>.CreateAsync(_context.Problems.OrderBy(p=>p.ProblemID)
                .AsNoTracking(), page ?? 1, pageSize));
        }

        // GET: Problems/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var problem = await _context.Problems
                .FirstOrDefaultAsync(m => m.ProblemID == id);
            if (problem == null)
            {
                return NotFound();
            }

            return View(problem);
        }

        // GET: Problems/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Problems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Name,Description,Format,SampleInput,SampleOutput,Note,Limitation")] Problem problem,
            IFormFile data)
        {
            if (data == null)
            {
                ModelState.AddModelError("Data", "Problem data can not be empty.");
            }
            if (ModelState.IsValid)
            {
                string defaultProblemID = "P1000";
                if (!_context.Problems.Any())
                {
                    problem.ProblemID = defaultProblemID;
                }
                else
                {
                    var lastProblemID = _context.Problems.OrderByDescending(p => p.ProblemID)
                        .First().ProblemID.Substring(1);
                    var thisProblemID = int.Parse(lastProblemID) + 1;
                    problem.ProblemID = "P" + thisProblemID.ToString();
                }
                using (var ms = new MemoryStream())
                {
                    var ct = data.CopyToAsync(ms);
                    await ct;
                    problem.Data = ms.ToArray();
                }
                problem.DataHash = GetMd5Hash(problem.Data);
                _context.Add(problem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(problem);
        }

        // GET: Problems/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var problem = await _context.Problems.FindAsync(id);
            if (problem == null)
            {
                return NotFound();
            }
            return View(problem);
        }

        // POST: Problems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id,
            [Bind("ProblemID,Name,Description,Format,SampleInput,SampleOutput,Note,Limitation")] Problem problem,
            IFormFile data)
        {
            if (id != problem.ProblemID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (data != null)
                    {
                        using (var ms = new MemoryStream())
                        {
                            var ct = data.CopyToAsync(ms);
                            await ct;
                            problem.Data = ms.ToArray();
                            problem.DataHash = GetMd5Hash(problem.Data);
                        }
                        _context.Update(problem);
                    }
                    else
                    {
                        _context.Problems.Attach(problem);
                        var entry = _context.Entry(problem);
                        entry.State = EntityState.Modified;
                        entry.Property(e => e.Data).IsModified = false;
                        entry.Property(e => e.DataHash).IsModified = false;
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProblemExists(problem.ProblemID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(problem);
        }

        // GET: Problems/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var problem = await _context.Problems
                .FirstOrDefaultAsync(m => m.ProblemID == id);
            if (problem == null)
            {
                return NotFound();
            }

            return View(problem);
        }

        // POST: Problems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var problem = await _context.Problems.FindAsync(id);
            _context.Problems.Remove(problem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProblemExists(string id)
        {
            return _context.Problems.Any(e => e.ProblemID == id);
        }

        // GET: Problems/DownloadDataset/5
        public async Task<IActionResult> DownloadDataset(string id, string key)
        {
            var judgeSettings = _configuration.GetSection("Judge").GetChildren();
            foreach (var section in judgeSettings)
            {
                var judgeKey = section.GetValue<string>("Key");
                if (judgeKey == key)
                {
                    var problem = await _context.Problems.FindAsync(id);
                    return File(problem.Data, System.Net.Mime.MediaTypeNames.Application.Zip, $"{id}.zip");
                }
            }
            return Unauthorized();
        }
    }
}

web/Controllers/RecordsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using RabbitMQ.Client;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using YAOJ.Data;
using YAOJ.Models;

namespace YAOJ.Controllers
{
    public class JudgeRequest
    {
        public int userID;
        public int recordID;
        public string problemID;
        public string language;
        public string sourceCode;
        public string dataHash;

        public static JudgeRequest CreateJudgeRequest(Record record)
        {
            return new JudgeRequest
            {
                recordID = record.RecordID,
                problemID = record.ProblemID,
                language = record.Language,
                userID = record.UserID,
                dataHash = record.Problem.DataHash,
                sourceCode = record.SourceCode
            };
        }
        
    }

    public class RecordsController : Controller
    {
        public void SendJudgeRequest(Record record)
        {
            var factory = new ConnectionFactory()
            {
                HostName = _rabbitMQConfig["Server"],
                UserName = _rabbitMQConfig["Username"],
                Password = _rabbitMQConfig["Password"],
                Port = int.Parse(_rabbitMQConfig["Port"])
            };
            using (var connection = factory.CreateConnection())
            using (var channel = connection.CreateModel())
            {
                channel.QueueDeclare(queue: "yaoj_queue", durable: true, exclusive: false,
                    autoDelete: false, arguments: null);

                var request = JudgeRequest.CreateJudgeRequest(record);
                var jsonifiedMessage = JsonConvert.SerializeObject(request);
                var body = Encoding.UTF8.GetBytes(jsonifiedMessage);

                var properties = channel.CreateBasicProperties();
                properties.Persistent = true;

                channel.BasicPublish(exchange: "", routingKey: "yaoj_queue",
                    basicProperties: properties, body: body);
            }
        }

        private readonly DataContext _context;
        private readonly IConfiguration _configuration;
        private readonly Dictionary<string, string> _rabbitMQConfig;

        public RecordsController(DataContext context, IConfiguration configuration,
             Dictionary<string, string> rabbitMQConfig)
        {
            _context = context;
            _configuration = configuration;
            _rabbitMQConfig = rabbitMQConfig;
        }

        // GET: Records
        public async Task<IActionResult> Index(string searchProblemID,
            string currentFilter, int? page)
        {
            ViewData["CurrentFilter"] = searchProblemID;

            if (searchProblemID != null)
            {
                page = 1;
            }
            else
            {
                searchProblemID = currentFilter;
            }

            var records = from s in _context.Records select s;
            if (!String.IsNullOrEmpty(searchProblemID))
            {
                records = records.Where(s => s.ProblemID == searchProblemID);
            }
            records = records.Include(s => s.Problem).Include(s => s.User)
                .OrderByDescending(i => i.RecordID);

            int pageSize = 10;

            return View(await PaginatedList<Record>.CreateAsync(records.AsNoTracking(), page ?? 1, pageSize));
        }

        // GET: Records/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var record = await _context.Records
                .Include(r => r.Problem)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.RecordID == id);
            if (record == null)
            {
                return NotFound();
            }

            return View(record);
        }

        // GET: Records/Create/P1000
        public IActionResult Create(string id)
        {
            ViewData["ProblemID"] = id;
            return View();
        }

        // POST: Records/Create/P1000
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            string id,
            [Bind("Language,SourceCode")] Record record)
        {
            if (ModelState.IsValid)
            {
                record.ProblemID = id;
                record.Problem = _context.Problems.First(i => i.ProblemID == id);
                record.UserID = 1;
                record.Status = Status.NA;
                record.UsedMemory = 0;
                record.UsedTime = 0;
            
                _context.Records.Add(record);
                await _context.SaveChangesAsync();
                SendJudgeRequest(record);
                return RedirectToAction(nameof(Index));
            }
            return View(record);
        }
        
        // GET: Records/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var record = await _context.Records
                .Include(r => r.Problem)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.RecordID == id);
            if (record == null)
            {
                return NotFound();
            }

            return View(record);
        }

        // POST: Records/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var record = await _context.Records.FindAsync(id);
            _context.Records.Remove(record);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: Records/Update/5
        [HttpPost]
        public async Task<IActionResult> Update(int id, string text, string status,
            string usedTime, string usedMemory)
        {
            var record = await _context.Records
                .Include(r => r.Problem)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.RecordID == id);
            if (record == null)
            {
                return NotFound();
            }

            record.Status = (Status) Enum.Parse(typeof(Status), status);
            record.JudgeText = text;
            record.UsedTime = double.Parse(usedTime);
            record.UsedMemory = int.Parse(usedMemory);

            _context.Update(record);
            await _context.SaveChangesAsync();
            return Content("Succeeded!");
        }

        private bool RecordExists(int id)
        {
            return _context.Records.Any(e => e.RecordID == id);
        }
    }
}

web/Views/Records/Create.cshtml
@model YAOJ.Models.Record

@{
    ViewData["Title"] = "Submission";
}

<h2>Submit to Problem @ViewData["ProblemID"]</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Language" class="control-label"></label>
                <input asp-for="Language" class="form-control" />
                <span asp-validation-for="Language" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SourceCode" class="control-label"></label>
                <textarea asp-for="SourceCode" class="form-control" rows=10></textarea>
                <span asp-validation-for="SourceCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Submissions</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

web/Views/Records/Delete.cshtml
@model YAOJ.Models.Record

@{
    ViewData["Title"] = "Delete Submission";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this submission?</h3>
<hr />
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Problem)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Problem.ProblemID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SourceCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SourceCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UsedTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UsedTime) s
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UsedMemory)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UsedMemory) MB
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="RecordID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to Submissions</a>
    </form>
</div>

web/Views/Records/Details.cshtml
@model YAOJ.Models.Record

@{
    ViewData["Title"] = "Submission Details";
}

<h2>Submission Details</h2>
<hr />

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Problem)
        </dt>
        <dd>
            <a asp-controller="Problems" asp-action="Details" asp-route-id="@Model.ProblemID">
                @Html.DisplayFor(model => model.Problem.ProblemID)
            </a>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UsedTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UsedTime) s
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UsedMemory)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UsedMemory) MB
        </dd>
    </dl>

    <h3>
        @Html.DisplayNameFor(model => model.JudgeText)
    </h3>
    <pre>@Html.DisplayFor(model => model.JudgeText)</pre>

    <h3>
        @Html.DisplayNameFor(model => model.SourceCode)
    </h3>
    <pre>@Html.DisplayFor(model => model.SourceCode)</pre>
</div>
<div>
    <a asp-action="Delete" asp-route-id="@Model.RecordID">Delete</a> |
    <a asp-action="Index">Back to Submissions</a>
</div>

web/Views/Records/Index.cshtml
@model PaginatedList<YAOJ.Models.Record>

@{
    ViewData["Title"] = "Submissions";
}

<h2>Submissions</h2>
<hr />

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by Problem ID: <input type="text" name="searchProblemID" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().RecordID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Problem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Language)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().UsedTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().UsedMemory)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.RecordID">
                        @Html.DisplayFor(modelItem => item.RecordID)
                    </a>
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.RecordID">
                        @Html.DisplayFor(modelItem => item.Status)
                    </a>
                </td>
                <td>
                    <a asp-controller="Problems" asp-action="Details" asp-route-id="@item.ProblemID">
                        @Html.DisplayFor(modelItem => item.ProblemID) - @Html.DisplayFor(modelItem => item.Problem.Name)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Language)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UsedTime) s
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UsedMemory) MB
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>